[window]
padding = { x = 10, y = 10 }

[font]
size = 11
normal = { family="FiraCode Nerd Font Propo", style="Retina"}
# normal = { family="JetBrainsMono NFM", style="Regular"}
# normal = { family = "ComicShannsMono Nerd Font Propo", style="Regular"}

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
# TERM = "xterm256-color"
