set -g focus-events on
set -g status-style bg=default
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre

set -g mouse on

set -g default-terminal "xterm-256color"

set -gu default-command

set -g default-shell "$SHELL"

set -sg terminal-overrides ",*:RGB"

set -sg escape-time 50

# vim key bindings
set -s copy-command "pbcopy"
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-g display-popup -h 75% -w 75% -E "lazygit"
bind C-d display-popup -h 75% -w 75% -E "lazydocker"

set -g base-index 1
setw -g pane-base-index 1

# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
